CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    student_number VARCHAR(30) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    course VARCHAR(100) NOT NULL,
    year_level INT NOT NULL,
    email VARCHAR(120) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_students_student_number UNIQUE (student_number)
);

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_students_updated_at ON students;
CREATE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO students (student_number, first_name, last_name, course, year_level, email, phone) VALUES
('2026-0001', 'Jose', 'Reyes', 'BSIT', 1, 'jose.reyes@example.com', '09171000001'),
('2026-0002', 'Maria', 'Santos', 'BSCS', 2, 'maria.santos@example.com', '09171000002'),
('2026-0003', 'Juan', 'Cruz', 'BSECE', 3, 'juan.cruz@example.com', '09171000003'),
('2026-0004', 'Ana', 'Garcia', 'BSIS', 1, 'ana.garcia@example.com', '09171000004'),
('2026-0005', 'Carlo', 'Mendoza', 'BSBA', 2, 'carlo.mendoza@example.com', '09171000005'),
('2026-0006', 'Liza', 'Flores', 'BSN', 4, 'liza.flores@example.com', '09171000006'),
('2026-0007', 'Ramon', 'Bautista', 'BSIT', 3, 'ramon.bautista@example.com', '09171000007'),
('2026-0008', 'Grace', 'Villanueva', 'BSCS', 1, 'grace.villanueva@example.com', '09171000008'),
('2026-0009', 'Mark', 'Ramos', 'BSECE', 2, 'mark.ramos@example.com', '09171000009'),
('2026-0010', 'Cynthia', 'Torres', 'BSA', 4, 'cynthia.torres@example.com', '09171000010'),
('2026-0011', 'Dennis', 'Castillo', 'BSIT', 1, 'dennis.castillo@example.com', '09171000011'),
('2026-0012', 'Patricia', 'Aquino', 'BSBA', 3, 'patricia.aquino@example.com', '09171000012'),
('2026-0013', 'Eduardo', 'Dela Cruz', 'BSCS', 2, 'eduardo.delacruz@example.com', '09171000013'),
('2026-0014', 'Maricel', 'Gonzales', 'BSIS', 4, 'maricel.gonzales@example.com', '09171000014'),
('2026-0015', 'Rico', 'Hernandez', 'BSECE', 1, 'rico.hernandez@example.com', '09171000015'),
('2026-0016', 'Joanna', 'Lopez', 'BSN', 2, 'joanna.lopez@example.com', '09171000016'),
('2026-0017', 'Felix', 'Navarro', 'BSA', 3, 'felix.navarro@example.com', '09171000017'),
('2026-0018', 'Rowena', 'Pascual', 'BSIT', 4, 'rowena.pascual@example.com', '09171000018'),
('2026-0019', 'Arnel', 'Salazar', 'BSCS', 1, 'arnel.salazar@example.com', '09171000019'),
('2026-0020', 'Teresita', 'Valdez', 'BSBA', 2, 'teresita.valdez@example.com', '09171000020'),
('2026-0021', 'Bryan', 'Aguilar', 'BSECE', 3, 'bryan.aguilar@example.com', '09171000021'),
('2026-0022', 'Maribel', 'Buenaventura', 'BSIS', 1, 'maribel.buenaventura@example.com', '09171000022'),
('2026-0023', 'Rolando', 'Concepcion', 'BSN', 4, 'rolando.concepcion@example.com', '09171000023'),
('2026-0024', 'Cristina', 'Delos Reyes', 'BSA', 2, 'cristina.delosreyes@example.com', '09171000024'),
('2026-0025', 'Nestor', 'Espiritu', 'BSIT', 3, 'nestor.espiritu@example.com', '09171000025'),
('2026-0026', 'Florinda', 'Fajardo', 'BSCS', 1, 'florinda.fajardo@example.com', '09171000026'),
('2026-0027', 'Gilbert', 'Guevarra', 'BSECE', 2, 'gilbert.guevarra@example.com', '09171000027');

INSERT INTO users (username, password_hash) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
('student', '703b0a3d6ad75b649a28adde7d83c6251da457549263bc7ff45ec709b0a8448b');
